---
title: "MGMT 47400: Predictive Analytics"
subtitle: "Mitch. Daniels School of Business, Purdue University"
---

<!--- # IMPORTANT REFERENCE: https://www.youtube.com/watch?v=uimdXPZc40I&list=PLkrJrLs7xfbXcEKhTCKRSr2VXH4yiBeXo&index=4 --->

<br>

<center>

*IMPORTANT*

*This document does not replace the official material in the course brightspace page*

</center>

<br>

## Course Description and Objectives

The course enables students to navigate the entire predictive analytics pipeline skillfully—from data preparation and exploration to modeling, assessment, and interpretation. Throughout the course, learners engage with real-world examples and hands-on labs emphasizing essential programming and analytical skills. By exploring topics such as linear and logistic regression, classification, resampling methods, regularization techniques, tree-based approaches, support vector machines, and advanced learning paradigms (including neural networks and unsupervised methods), participants gain a robust theoretical understanding and practical experience. Ultimately, students will leave the course equipped to apply predictive models to data-driven problems, communicate their findings to diverse audiences, and critically evaluate model performance to inform strategic decision-making across various business contexts.

**Course Website**: [https://davi-moreira.github.io/2025S_predictive_analytics_purdue_MGMT47400/](https://davi-moreira.github.io/2025S_predictive_analytics_purdue_MGMT47400/){target="_blank"}

### Instructor: [Professor Davi Moreira](https://davi-moreira.github.io)

-   Email: [dmoreira\@purdue.edu](mailto:dmoreira@purdue.edu)
-   Office: Young Hall 414
-   Virtual Office hours: *Zoom link in your Course Brightspace Page*
-   Individual Appointments: *Book time with me through the link in the course syllabus on your Course Brightspace Page or by appointment.*

## Learning Outcomes

By the conclusion of this course, students will be able to:

1.  **Explain Core Predictive Analytics Concepts:** Articulate key principles of statistical learning and predictive analytics, including fundamental terminology, modeling strategies, and the role of data-driven insights in business contexts.

2.  **Prepare and Explore Data Effectively:** Demonstrate proficiency in cleaning, organizing, and exploring datasets, applying tools and techniques for data preprocessing, feature engineering, and exploratory analysis.

3.  **Implement Diverse Modeling Techniques:** Construct predictive models using linear and logistic regression, classification methods, resampling procedures, and regularization techniques.

4.  **Assess and Interpret Model Performance:** Evaluate the accuracy, robustness, and interpretability of predictive models, critically examining issues such as overfitting, bias-variance trade-offs, and cross-validation results.

5.  **Communicate Analytical Findings:** Present analytical outcomes and model interpretations to technical and non-technical audiences, crafting clear, concise, and visually effective reports or presentations.

6.  **Integrate Predictive Analytics into Decision-Making:** Recommend actionable strategies based on model findings, demonstrating the ability to align analytical results with organizational objectives and inform evidence-based decision processes.

## Course Materials

-   **Textbooks (Required): [ISLP](https://www.statlearning.com/){target="_blank"}** James, G., Witten, D., Hastie, T., & Tibshirani, R. (2023). An Introduction to Statistical Learning with Applications in Python. Springer. https://doi.org/10.1007/978-1-0716-2926-2. Download here: [https://www.statlearning.com/](https://www.statlearning.com/){target="_blank"}

-   **Computing (Required):** A laptop or desktop with internet access and the capability to run Python code through Google Colab: [https://colab.research.google.com/](https://colab.research.google.com/){target="_blank"}.

-   **Software (Required):** [Google Colab](https://colab.research.google.com/){target="_blank"} is a cloud-based platform that requires no software installation on your local machine; it is accessible through a modern web browser such as Google Chrome, Mozilla Firefox, Microsoft Edge, or Safari. To use Google Colab, you need a Google account and a stable internet connection. While optional, having tools like a local Python installation (e.g., Anaconda) or a Python IDE (e.g., Jupyter Notebook or VS Code) can be helpful for offline development. Additionally, browser extensions, such as those for VS Code integration, can enhance your experience but are not required. This makes Google Colab convenient and easy for Python programming and data science tasks.

## Course Infra-structure

**Brightspace:** The Course Brightspace Page <https://purdue.brightspace.com/> should be checked on a regular basis for announcements and course material.
