---
title: "Schedule"
author: "Davi Moreira"
# date-modified: "last-modified"
# date: "2025-01-13"
# date-format: "MMM D, YYYY"
# listing:
#   - id: schedule
#     contents:
#       - topics/topic-*.qmd
#     type: table
#     fields: [week, title, subtitle, date]
#     field-display-names:
#       week: "Week"
#       title: "Topic"
#       description: "Dates"
#       subtitle: "Description"
#     date-format: "MMMM DD, YYYY to MMMM DD, YYYY"
#     sort: [filename]
#     sort-ui: false
#     filter-ui: false
 #tbl-colwidths: [5,20,50,25]
editor: visual
---

| Week | Topic | Readings [ISLP](https://www.statlearning.com/){target="_blank"} | Material\* | Supplementary Materials |
|------------|------------|------------|------------|--------------------------|
| Week 1 | Syllabus, Logistics, and Introduction. | Ch. 1; Ch. 2; | [slides](/lecture_slides/02_data_organization_decision/02_data_organization_decision.html){target="_blank"}<br>[book lab](https://colab.research.google.com/github/intro-stat-learning/ISLP_labs/blob/v2.2/Ch02-statlearn-lab.ipynb){target="_blank"} | - [**Video**: Statistical Learning: 2.1 Introduction to Regression Models](https://www.youtube.com/watch?v=ox0cKk7h4o0&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=5){target="_blank"}<br>- [**Video**: Statistical Learning: 2.2 Dimensionality and Structured Models](https://www.youtube.com/watch?v=uFwbrdvrAJs&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=5){target="_blank"}<br>- [**Video**: Statistical Learning: 2.3 Model Selection and Bias Variance Tradeoff](https://www.youtube.com/watch?v=pvcEQfcO3pk&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=6){target="_blank"}<br>- [**Video**: Statistical Learning: 2.4 Classification](https://www.youtube.com/watch?v=BMJQ3LQ_QKU&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=7){target="_blank"}<br>- [**Video**: Statistical Learning: 2.Py Data Types, Arrays, and Basics - 2023](https://www.youtube.com/watch?v=Cv1sx_HNRHM&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=3){target="_blank"}<br>- [**Video**: Statistical Learning: 2.Py.3 Graphics - 2023](https://www.youtube.com/watch?v=JykmuvCY130&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=4){target="_blank"}<br>- [**Video**: Statistical Learning: 2.Py Indexing and Dataframes - 2023](https://www.youtube.com/watch?v=Zcb-1JmmO_U&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=5){target="_blank"} |
| Week 2 | Linear Regression | Ch. 3. | [slides](#){target="_blank"}<br>[book lab](#){target="_blank"} | - [**Video**: Statistical Learning: 3.1 Simple linear regression](https://www.youtube.com/watch?v=vCHtY6Me5FI&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=9){target="_blank"}<br>- [**Video**: Statistical Learning: 3.2 Hypothesis Testing and Confidence Intervals](https://www.youtube.com/watch?v=3GiWpRfkSjc&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=10){target="_blank"}<br>- [**Video**: Statistical Learning: 3.3 Multiple Linear Regression](https://www.youtube.com/watch?v=o9hoLdylWKo&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=11){target="_blank"}<br>- [**Video**: Statistical Learning: 3.4 Some important questions](https://www.youtube.com/watch?v=50sv4UTjE90&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=12){target="_blank"}<br>- [**Video**: Statistical Learning: 3.5 Extensions of the Linear Model](https://www.youtube.com/watch?v=dEBQmiXv9fk&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=13){target="_blank"}<br>- [**Video**: Statistical Learning: 3.Py Linear Regression and statsmodels Package - 2023](https://www.youtube.com/watch?v=mKalBNrxToU&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=6){target="_blank"}<br>- [**Video**: Statistical Learning: 3.Py Multiple Linear Regression Package - 2023](https://www.youtube.com/watch?v=pGOr3HZhUZQ&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=7){target="_blank"}<br>- [**Video**: Statistical Learning: 3.Py Interactions, Qualitative Predictors and Other Details I 2023](https://www.youtube.com/watch?v=d0K2mDclyXM&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=8){target="_blank"} |

\* The course slides and labs are based on the [ISLP](https://www.statlearning.com/){target="_blank"} book, [*"An Introduction to Statistical Learning with Applications in Python"*](https://www.statlearning.com/){target="_blank"} by James, G., Witten, D., Hastie, T., and Tibshirani, R., and have been adapted to suit the specific needs of our course.
